In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [4]:
df = pd.read_csv('data/Bakery sales.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234005 entries, 0 to 234004
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   Unnamed: 0     234005 non-null  int64  
 1   date           234005 non-null  object 
 2   time           234005 non-null  object 
 3   ticket_number  234005 non-null  float64
 4   article        234005 non-null  object 
 5   Quantity       234005 non-null  float64
 6   unit_price     234005 non-null  object 
dtypes: float64(2), int64(1), object(4)
memory usage: 12.5+ MB


In [9]:
df.iloc[:,0]

0              0
1              1
2              4
3              5
4              8
           ...  
234000    511387
234001    511388
234002    511389
234003    511392
234004    511395
Name: Unnamed: 0, Length: 234005, dtype: int64

In [10]:
df = df.drop(columns = 'Unnamed: 0')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234005 entries, 0 to 234004
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   date           234005 non-null  object 
 1   time           234005 non-null  object 
 2   ticket_number  234005 non-null  float64
 3   article        234005 non-null  object 
 4   Quantity       234005 non-null  float64
 5   unit_price     234005 non-null  object 
dtypes: float64(2), object(4)
memory usage: 10.7+ MB


In [13]:
df['unit_price']

0         0,90 €
1         1,20 €
2         1,20 €
3         1,15 €
4         1,20 €
           ...  
234000    0,15 €
234001    1,20 €
234002    0,15 €
234003    1,30 €
234004    1,30 €
Name: unit_price, Length: 234005, dtype: object

In [14]:
def convert_currency_format(value):
    value = value.replace('€', '')
    value = value.replace(' ', '')
    value = value.replace(',', '.')
    return float(value)

In [17]:
df['unit_price'] = df['unit_price'].astype(str)
df['unit_price'] = df['unit_price'].apply(convert_currency_format)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234005 entries, 0 to 234004
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   date           234005 non-null  object 
 1   time           234005 non-null  object 
 2   ticket_number  234005 non-null  float64
 3   article        234005 non-null  object 
 4   Quantity       234005 non-null  float64
 5   unit_price     234005 non-null  float64
dtypes: float64(3), object(3)
memory usage: 10.7+ MB


In [19]:
df = df.rename(columns={'Quantity': 'quantity'})

In [27]:
df.head()

date   time  ticket_number               article  quantity  \
0  2021-01-02  08:38       150040.0              BAGUETTE       1.0   
1  2021-01-02  08:38       150040.0      PAIN AU CHOCOLAT       3.0   
2  2021-01-02  09:14       150041.0      PAIN AU CHOCOLAT       2.0   
3  2021-01-02  09:14       150041.0                  PAIN       1.0   
4  2021-01-02  09:25       150042.0  TRADITIONAL BAGUETTE       5.0   

   unit_price  
0        0.90  
1        1.20  
2        1.20  
3        1.15  
4        1.20

In [29]:
df['date'] = df['date'].astype(str)
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234005 entries, 0 to 234004
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype         
---  ------         --------------   -----         
 0   date           234005 non-null  datetime64[ns]
 1   time           234005 non-null  object        
 2   ticket_number  234005 non-null  float64       
 3   article        234005 non-null  object        
 4   quantity       234005 non-null  float64       
 5   unit_price     234005 non-null  float64       
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 10.7+ MB


In [31]:
df.head()

date   time  ticket_number               article  quantity  unit_price
0 2021-01-02  08:38       150040.0              BAGUETTE       1.0        0.90
1 2021-01-02  08:38       150040.0      PAIN AU CHOCOLAT       3.0        1.20
2 2021-01-02  09:14       150041.0      PAIN AU CHOCOLAT       2.0        1.20
3 2021-01-02  09:14       150041.0                  PAIN       1.0        1.15
4 2021-01-02  09:25       150042.0  TRADITIONAL BAGUETTE       5.0        1.20

In [32]:
df['time'] = df['time'].astype(str)
df['time'] = df['time'] + ':00'

In [34]:
df['time'] = pd.to_timedelta(df['time'])

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234005 entries, 0 to 234004
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype          
---  ------         --------------   -----          
 0   date           234005 non-null  datetime64[ns] 
 1   time           234005 non-null  timedelta64[ns]
 2   ticket_number  234005 non-null  float64        
 3   article        234005 non-null  object         
 4   quantity       234005 non-null  float64        
 5   unit_price     234005 non-null  float64        
dtypes: datetime64[ns](1), float64(3), object(1), timedelta64[ns](1)
memory usage: 10.7+ MB


In [36]:
df['datetime'] = df['date'] + df['time']

In [37]:
df.head()

date            time  ticket_number               article  quantity  \
0 2021-01-02 0 days 08:38:00       150040.0              BAGUETTE       1.0   
1 2021-01-02 0 days 08:38:00       150040.0      PAIN AU CHOCOLAT       3.0   
2 2021-01-02 0 days 09:14:00       150041.0      PAIN AU CHOCOLAT       2.0   
3 2021-01-02 0 days 09:14:00       150041.0                  PAIN       1.0   
4 2021-01-02 0 days 09:25:00       150042.0  TRADITIONAL BAGUETTE       5.0   

   unit_price            datetime  
0        0.90 2021-01-02 08:38:00  
1        1.20 2021-01-02 08:38:00  
2        1.20 2021-01-02 09:14:00  
3        1.15 2021-01-02 09:14:00  
4        1.20 2021-01-02 09:25:00

In [38]:
df.describe()

date                       time  \
count                         234005                     234005   
mean   2021-11-30 11:33:31.049336576  0 days 11:34:00.873827482   
min              2021-01-02 00:00:00            0 days 07:01:00   
25%              2021-07-03 00:00:00            0 days 09:42:00   
50%              2021-11-04 00:00:00            0 days 11:06:00   
75%              2022-05-31 00:00:00            0 days 12:21:00   
max              2022-09-30 00:00:00            0 days 20:01:00   
std                              NaN  0 days 02:45:25.077746610   

       ticket_number       quantity     unit_price  \
count  234005.000000  234005.000000  234005.000000   
mean   219201.258738       1.538377       1.662195   
min    150040.000000    -200.000000       0.000000   
25%    184754.000000       1.000000       1.100000   
50%    218807.000000       1.000000       1.200000   
75%    253927.000000       2.000000       1.500000   
max    288913.000000     200.000000      60.000000   
std     40053.223896       1.289603       1.722720   

                            datetime  
count                         234005  
mean   2021-11-30 23:07:31.923163904  
min              2021-01-02 08:38:00  
25%              2021-07-03 11:21:00  
50%              2021-11-04 11:56:00  
75%              2022-05-31 09:18:00  
max              2022-09-30 18:56:00  
std                              NaN

In [39]:
df[df['quantity']<0]

date            time  ticket_number               article  \
448    2021-01-03 0 days 10:41:00       150265.0              BAGUETTE   
1162   2021-01-05 0 days 19:00:00       150738.0         SPECIAL BREAD   
1163   2021-01-05 0 days 19:00:00       150738.0     DIVERS PATISSERIE   
1164   2021-01-05 0 days 19:00:00       150738.0    DIVERS BOULANGERIE   
1467   2021-01-08 0 days 11:58:00       150941.0                 COUPE   
...           ...             ...            ...                   ...   
233054 2022-09-27 0 days 18:03:00       288312.0                 COUPE   
233055 2022-09-27 0 days 18:03:00       288312.0  TRADITIONAL BAGUETTE   
233056 2022-09-27 0 days 18:03:00       288312.0       CEREAL BAGUETTE   
233553 2022-09-29 0 days 11:55:00       288639.0          BOISSON 33CL   
233554 2022-09-29 0 days 11:55:00       288639.0            PLAT 7.60E   

        quantity  unit_price            datetime  
448         -1.0        0.90 2021-01-03 10:41:00  
1162        -1.0        2.40 2021-01-05 19:00:00  
1163        -1.0        6.00 2021-01-05 19:00:00  
1164        -1.0        2.00 2021-01-05 19:00:00  
1467        -1.0        0.15 2021-01-08 11:58:00  
...          ...         ...                 ...  
233054      -2.0        0.15 2022-09-27 18:03:00  
233055      -1.0        1.30 2022-09-27 18:03:00  
233056      -3.0        1.35 2022-09-27 18:03:00  
233553      -1.0        1.50 2022-09-29 11:55:00  
233554      -1.0        7.60 2022-09-29 11:55:00  

[1295 rows x 7 columns]

Negative values in the quantity column were found, this can mean that these transactions were refunds and product returns. We can take a closer look to this records with negative quantities, for example the one at 2021-01-05, SPECIAL BREAD, DIVERS PATISSERIE, and DIVERS BOULANGERIE, with the ticket number of 150738.0

In [49]:
start_time = pd.Timestamp('2021-01-05' + ' 18:40') 
end_time = pd.Timestamp('2021-01-05' + ' 19:00')

df[(df['datetime'] >= start_time) & (df['datetime'] <= end_time)]

date            time  ticket_number               article  \
1156 2021-01-05 0 days 18:49:00       150734.0               BANETTE   
1157 2021-01-05 0 days 18:49:00       150735.0  TRADITIONAL BAGUETTE   
1158 2021-01-05 0 days 18:51:00       150736.0  TRADITIONAL BAGUETTE   
1159 2021-01-05 0 days 18:58:00       150737.0     DIVERS PATISSERIE   
1160 2021-01-05 0 days 18:58:00       150737.0    DIVERS BOULANGERIE   
1161 2021-01-05 0 days 18:58:00       150737.0         SPECIAL BREAD   
1162 2021-01-05 0 days 19:00:00       150738.0         SPECIAL BREAD   
1163 2021-01-05 0 days 19:00:00       150738.0     DIVERS PATISSERIE   
1164 2021-01-05 0 days 19:00:00       150738.0    DIVERS BOULANGERIE   
1165 2021-01-05 0 days 19:00:00       150739.0     DIVERS PATISSERIE   
1166 2021-01-05 0 days 19:00:00       150739.0         SPECIAL BREAD   

      quantity  unit_price            datetime  
1156       2.0        1.05 2021-01-05 18:49:00  
1157       1.0        1.20 2021-01-05 18:49:00  
1158       1.0        1.20 2021-01-05 18:51:00  
1159       1.0        6.00 2021-01-05 18:58:00  
1160       1.0        2.00 2021-01-05 18:58:00  
1161       1.0        2.40 2021-01-05 18:58:00  
1162      -1.0        2.40 2021-01-05 19:00:00  
1163      -1.0        6.00 2021-01-05 19:00:00  
1164      -1.0        2.00 2021-01-05 19:00:00  
1165       1.0        6.00 2021-01-05 19:00:00  
1166       1.0        2.40 2021-01-05 19:00:00

We observe that those same three items were bought a couple of minutes before with the ticket number 150737.0, this shows that these negative numbers may represent, in most cases, returns or cancelled purchases.

For the purposes of the analysis, the sales and product returns will be separated into different dataframes. One dataframe will be called **sales** and the other **returns**.

In [53]:
sales = df[df['quantity'] > 0]

In [54]:
returns = df[df['quantity'] < 0]

In [55]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
Index: 232710 entries, 0 to 234004
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype          
---  ------         --------------   -----          
 0   date           232710 non-null  datetime64[ns] 
 1   time           232710 non-null  timedelta64[ns]
 2   ticket_number  232710 non-null  float64        
 3   article        232710 non-null  object         
 4   quantity       232710 non-null  float64        
 5   unit_price     232710 non-null  float64        
 6   datetime       232710 non-null  datetime64[ns] 
dtypes: datetime64[ns](2), float64(3), object(1), timedelta64[ns](1)
memory usage: 14.2+ MB


In [56]:
returns.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1295 entries, 448 to 233554
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype          
---  ------         --------------  -----          
 0   date           1295 non-null   datetime64[ns] 
 1   time           1295 non-null   timedelta64[ns]
 2   ticket_number  1295 non-null   float64        
 3   article        1295 non-null   object         
 4   quantity       1295 non-null   float64        
 5   unit_price     1295 non-null   float64        
 6   datetime       1295 non-null   datetime64[ns] 
dtypes: datetime64[ns](2), float64(3), object(1), timedelta64[ns](1)
memory usage: 80.9+ KB
